language: python
python:
  - "2.7"

virtualenv:
  system_site_packages: true

env:
  - VERSION="7.0" ODOO_REPO="odoo/odoo"
  - VERSION="7.0" ODOO_REPO="OCA/OCB"

before_install:
  - git clone https://github.com/OCA/account-invoicing $HOME/account-invoicing -b 7.0
  - git clone https://github.com/OCA/account-financial-tools $HOME/account-financial-tools -b 7.0
  - git clone https://github.com/OCA/webkit-tools $HOME/webkit-tools -b 7.0
  - git clone https://github.com/OCA/account-payment $HOME/account-payment -b 7.0

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git $HOME/maintainer-quality-tools
  - export PATH=$HOME/maintainer-quality-tools/travis:$PATH
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  coveralls
